### ISSUE TITLE
Why unpublish "Cumulants from Möbius inversion"?

### ISSUE THREAD

**Issue by maresb** [hapax/hapax.github.io#1]
Hey there, I've been self-teaching myself about statistics (my background is in pure math and theoretical physics). I found this blog post a few months ago, and I found it really insightful and a pleasure to read. I wanted to share it with some friends, but I noticed that it was no longer on your website.

I wanted to compliment your writing, and also ask why you'd unpublish such a well-written article. Any chance of getting it back? Thanks!

**Comment by hapax** [comment]
Glad you found the blog post helpful! Thanks so much for the positive feedback :) I think I unpublished it because I wanted to add something about QFT but obviously never did. I've republished it!

**Comment by maresb** [comment]
Great, thanks for republishing! Please do ping me if you publish your QFT post and think of me. :smiley:
